version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/product-api
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always